config/routes.rb
Rails.application.routes.draw do

  root 'homepage#index'

  get "dashboard" => 'dashboard#index'

  resources :registrations, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resource :profile


end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates_presence_of :username, :email
  validates_uniqueness_of :username, :email
  validates :password, length: { in: 8..15 }
  validates :username, length: { minimum: 4 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :ensure_authenticated_user

  def ensure_authenticated_user
    redirect_to root_path unless current_user
  end

  def current_user
    User.find_by(id: session[:user_id])
  end
  helper_method :current_user

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :ensure_authenticated_user

  def index
    @user = current_user
  end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  skip_before_filter :ensure_authenticated_user

  def index
    @user = User.new
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  skip_before_filter :ensure_authenticated_user

  def new
    @user = User.new
  end

  def create
    @user = User.new(allowed_params)

    if @user.save
      flash[:notice] = "You have successfully registered"
      redirect_to dashboard_path
    else
      render 'homepage/index'
    end
  end

  private

  def allowed_params
    params.require(:user).permit(:username, :password, :email)
    # params.fetch(:user, {}).permit(:username, :first_name, :last_name, :password, :bio, :rant_frequency)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :ensure_authenticated_user

  def new
    @user = User.new
  end

  def create

    @user = User.find_by(username: params[:user][:username])

    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to dashboard_path
    elsif params[:user][:username] == "" || params[:user][:password] == ""
      @user = User.new(username: params[:user][:username])
      @user.errors[:base] << "Username / Password Required"
      render :new
    else
      @user = User.new(username: params[:user][:username])
      @user.errors[:base] << "Login Failed"
      render :new
    end
  end

  def destroy
    session.destroy
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homepage/index.html.haml
.homepage
  %section.clearfix
    .content_row.one
      .one_third
      .one_third
        = image_tag "http://i32.photobucket.com/albums/d8/mijikim926/ruby-answers-circle_zpscb76f9bd.png"
      .one_third
    .content_row.two
      .one_third
        = image_tag "http://i32.photobucket.com/albums/d8/mijikim926/ruby-question-circle_zps2669a072.png"
      .one_third
        = image_tag "http://i32.photobucket.com/albums/d8/mijikim926/ask-ruby-logo_zpsbfafa5cd.png", id: "logo"
      .one_third
        = image_tag "http://i32.photobucket.com/albums/d8/mijikim926/ruby-carrots-circle_zps28929462.png"
    .content_row.three
      .one_third
      .one_third
        - if @user.errors.any?
          .errors
            - @user.errors.full_messages.each do |message|
              %li * #{message}
        .register_one
          %h1 Join Us!
          %p Already a member?
          %br
          = link_to "Sign in here", new_session_path, class: "sign-in-link"
        .register_two
          = form_for @user, url: registrations_path, html: { class: "register-form" } do |f|
            .register-form-column#last_name
              = f.label :email
              = f.email_field :email
            .register-form-column#username
              = f.label :username
              = f.text_field :username
            .register-form-column#password
              = f.label :password
              = f.password_field :password
            #register
              = f.submit "Register", class: "register-button"
      .one_third

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Ask Ruby
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

  %body
    %header
    = yield

    -#- if current_user
    -#  %header
    -#    .navbar-logged-in
    -#      %section.clearfix
    -#        = link_to "Rant.ly", root_path, class: "header-word-logo"
    -#        %ul.top-nav
    -#          %li
    -#            = link_to "Dashboard", dashboard_path, class: "nav-list"
    -#          %li
    -#            = link_to "Following", session_path, class: "nav-list"
    -#          %li
    -#            = link_to "Favorites", session_path, class: "nav-list"
    -#          %li
    -#            = link_to "Search", session_path, class: "nav-list"
    -#          %li
    -#            = link_to "LOGOUT", session_path, class: "logout-button", method: :delete
    -#  = yield